name: Deploy the Product Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
  GITHUB_PAGES_BRANCH: gh-pages

  # options: "true" | "false"
  USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: "true"

  GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
  API_BASE_URL: "https://api.gateway.commonground.nu/api"
  NL_DESIGN_THEME_CLASSNAME: "epe-theme"
  DEV_ENVIRONMENT: "true"
  SHOW_CATEGORY: "false"
  SHOW_ORGANIZATION: "false"
  FAVICON_URL: "https://www.epe.nl/sites/default/themes/custom/toptasks_sub_theme/favicon/favicon-32x32.png"
  ORGANISATION_NAME: "Gemeente Epe"
  JUMBOTRON_IMAGE_URL: "https://raw.githubusercontent.com/ConductionNL/woo-website-epe/main/jumbotron.jpg"
  FOOTER_LOGO_URL: "false"
  FOOTER_LOGO_HREF: "https://www.epe.nl/"
  FOOTER_CONTENT: "https://raw.githubusercontent.com/ConductionNL/${{github.event.repository.name}}/main/FooterContent.json"
  FOOTER_CONTENT_HEADER: "heading-3"
  OIDN_NUMBER: "00000001001299992000"
  ENV_VARS_SET: "true"
  SECURITY_TXT_INTRO: "Information related to reporting security vulnerabilities of this site."
  SECURITY_TXT_CONTACT: "https://www.epe.nl/beveiligingslek-datalek-melden"
  SECURITY_TXT_EXPIRES: "2024-11-30T22:59:00.000Z"
  SECURITY_TXT_ENCRYPTION: "https://www.informatiebeveiligingsdienst.nl/pgp-sleutel/"
  SECURITY_TXT_ACKNOWLEDGEMENTS: "https://www.informatiebeveiligingsdienst.nl/responsible-disclosure/"
  SECURITY_TXT_LANGUAGES: "nl, en"
  SECURITY_TXT_CANONICAL: " "
  SECURITY_TXT_POLICY: "https://www.epe.nl/beveiligingslek-datalek-melden"
  SECURITY_TXT_HIRING: " "
  ANALYTICS_URL: "https://siteimproveanalytics.com/js/siteanalyze_6006019.js"
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the WOO Website Template Code
        uses: actions/checkout@v2
        with:
          repository: ConductionNL/woo-website-template
          ref: development

      # With special thanxs to https://github.com/SpicyPizza/create-envfile
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
          envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
          envkey_GATSBY_API_BASE_URL: ${{ env.API_BASE_URL }}
          envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
          envkey_GATSBY_DEV_ENVIRONMENT: ${{ env.DEV_ENVIRONMENT }}
          envkey_GATSBY_SHOW_CATEGORY: ${{ env.SHOW_CATEGORY }}
          envkey_GATSBY_SHOW_ORGANIZATION: ${{ env.SHOW_ORGANIZATION }}
          envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
          envkey_GATSBY_ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
          envkey_GATSBY_JUMBOTRON_IMAGE_URL: ${{ env.JUMBOTRON_IMAGE_URL }}
          envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
          envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
          envkey_GATSBY_FOOTER_CONTENT: ${{ env.FOOTER_CONTENT }}
          envkey_GATSBY_FOOTER_CONTENT_HEADER: ${{ env.FOOTER_CONTENT_HEADER }}
          envkey_GATSBY_OIDN_NUMBER: ${{ env.OIDN_NUMBER }}
          envkey_GATSBY_ENV_VARS_SET: ${{ env.ENV_VARS_SET }}
          envkey_GATSBY_SECURITY_TXT_INTRO: ${{ env.SECURITY_TXT_INTRO }}
          envkey_GATSBY_SECURITY_TXT_CONTACT: ${{ env.SECURITY_TXT_CONTACT }}
          envkey_GATSBY_SECURITY_TXT_EXPIRES: ${{ env.SECURITY_TXT_EXPIRES }}
          envkey_GATSBY_SECURITY_TXT_ENCRYPTION: ${{ env.SECURITY_TXT_ENCRYPTION }}
          envkey_GATSBY_SECURITY_TXT_ACKNOWLEDGEMENTS: ${{ env.SECURITY_TXT_ACKNOWLEDGEMENTS }}
          envkey_GATSBY_SECURITY_TXT_LANGUAGES: ${{ env.SECURITY_TXT_LANGUAGES }}
          envkey_GATSBY_SECURITY_TXT_CANONICAL: ${{ env.SECURITY_TXT_CANONICAL }}
          envkey_GATSBY_SECURITY_TXT_POLICY: ${{ env.SECURITY_TXT_POLICY }}
          envkey_GATSBY_SECURITY_TXT_HIRING: ${{ env.SECURITY_TXT_HIRING }}
          envkey_GATSBY_ANALYTICS_URL: ${{ env.ANALYTICS_URL }}
          directory: pwa/static
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: cd pwa && npm install

      - name: Install parcel/watcher
        run: cd pwa && npm install @parcel/watcher

      - name: Remove old Gatsby cache
        run: rm -rf pwa/.cache

      - name: Build application
        run: cd pwa && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: ${{ env.GITHUB_PAGES_BRANCH }}
          folder: pwa/public
